apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


bases:
- ../../prebuilt.image


patchesJson6902:
- path: hostname-patch.yaml
  target:
    group: networking.k8s.io
    version: v1beta1
    kind: Ingress
    name: centaur-ui-myapp